### PR TITLE
Add skeleton for documentation

### PR DESCRIPTION
**Pull request by ZedThree**
WIP while I set up Readthedocs.

This has been converted from `Documents/tex/index_of_acronyms_symbols/rp1.tex` and then manually cleaned up. It's left it with two separate tables of acronyms -- I guess these should be consolidated into a single table, unless there's some distinction between them?

Built documentation here: https://excalibur-neptune.readthedocs.io/en/add-docs/

Future pull requests should automatically build the documentation

### CODE REVIEW

**Comment by JosephThomasParker** [comment]
Nice - thanks Peter! The first list of acronyms was compiled manually from terms we used in reports.  The second list looks like it was scraped by @wayne-arter into a table.  I don't know if he wants the two lists combined, or if he was just testing the technology.

**Comment by ZedThree** [comment]
Ok, sounds like it should be squashed. There's quite a few gaps in the first table, it would be good to get them filled in too. Maybe also links to relevant organisations/websites?

Are there any other candidates for documents/reports that would be good to get into this documentation and publicly accessible?

**Comment by bendudson** [comment]
There was a Neptune community charter which was released with the calls, and perhaps could go somewhere. My concern is that that would be a fixed PDF at the moment, whereas what I think we want for this documentation is an editable live document. The PDF documents could go in the separate repo as a historical record, distinct from the current guidance in the documentation.

**Comment by JosephThomasParker** [comment]
> Maybe also links to relevant organisations/websites

This is a good idea, and neater in rst than tex.

I think it's only the charter that's a candidate for making public at the moment.  The core of the charter is just tex, so could be published on the repo in rst while still being a "living document".

**Comment by wayne-arter** [comment]
I’m afraid you’re looking at a work in progress as Joseph will confirm, and actually in fact only part of a piece of work to meet UKAEA D3.3 and D3.4 deliverables to Met Office due 20/3/21.
I realise this needs a telecon to explain, perhaps tomorrow?
Wayne

**Comment by bendudson** [comment]
Hi @wayne-arter is it a problem to put these in the documentation in their current form? Documentation is always a work in progress, but once it's in this repo it can be gradually improved over time (with PR reviews).

**Comment by JosephThomasParker** [comment]
The improved version can also be converted back to Latex reports using pandoc.

**Comment by wayne-arter** [comment]
Joseph and Will were both of the opinion that there were files in the D3.3/D3.4 directory that needed redacting by me(WA), so they omitted it from the github push.
It probably needs another day or so of my time and a bit of RSE support to get the directory into a state where anyone else could do much with it.

**Review by bendudson — DISMISSED** [review]
I vote for merging this to get the documentation started. More can be added when it has been redacted.

**Comment by ZedThree** [comment]
I've squashed the acronym tables into a single table, added the charter (assuming it doesn't need to be redacted), and added a very short page on writing documentation that just has links to the Sphinx docs for now.

**Review by JosephThomasParker — APPROVED** [review]

**Pull request merged**
